# Import latest keycloak image
FROM quay.io/keycloak/keycloak:latest as builder

# Set ENV variables for health metrics
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Expose HTTPS port
ENV KC_HTTPS_PORT=443
ENV KC_HOSTNAME_STRICT=false

# Create admin KC user
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=password

# Expose port 8443 for HTTPS
EXPOSE 443

# Copy jks cert to container for HTTPS
COPY {.JKS FILE PATH HERE} /opt/keycloak/