apiVersion: v1
kind: Pod
metadata:
  name: pf-nginx
  namespace: default
  labels:
    app: pf-nginx
spec:
  containers:
  - name: pf-nginx
    image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/combine-eks/nginx:1.27.0
    ports:
    - containerPort: 80
